# Generated by Django 4.2.11 on 2026-04-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(blank=True, help_text='13-digit Pakistani CNIC — null for community reporters', max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Required for Twilio SMS recovery notifications', max_length=15, null=True)),
                ('role', models.CharField(choices=[('owner', 'Bike Owner'), ('authority', 'Police Authority'), ('community', 'Community Reporter'), ('admin', 'System Admin')], default='owner', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verified — unverified users cannot file reports')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('badge_number', models.CharField(blank=True, help_text='Police badge number — authority role only', max_length=30, null=True, unique=True)),
                ('city', models.CharField(blank=True, help_text='Registered city — used to scope authority dashboard', max_length=80, null=True)),
                ('email_verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_verification_token_expires', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.UUIDField(blank=True, null=True)),
                ('password_reset_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. CREATED_REPORT, UPDATED_STATUS, LOGGED_RECOVERY', max_length=100)),
                ('table_affected', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state — NULL on CREATE actions', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state — NULL on DELETE actions', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
