# Generated by Django 4.2.11 on 2026-04-13 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuzzy_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='rapidfuzz WRatio confidence score used to identify this bike (0-100)', max_digits=5, null=True)),
                ('recovery_date', models.DateField()),
                ('recovery_city', models.CharField(max_length=80)),
                ('recovery_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='PostGIS POINT — used in recovery zone spatial analysis', null=True, srid=4326)),
                ('recovery_location_detail', models.TextField(blank=True, null=True)),
                ('bike_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('stripped', 'Stripped'), ('burnt', 'Burnt')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('evidence_photos', models.JSONField(blank=True, default=list, help_text="Array of UUID filenames: ['uuid1.jpg', 'uuid2.jpg']. Max 5 files, 2MB each.", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'recovery_records',
            },
        ),
        migrations.CreateModel(
            name='TheftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theft_date', models.DateField(help_text='Date the theft occurred — not necessarily today')),
                ('theft_city', models.CharField(max_length=80)),
                ('theft_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='PostGIS POINT (longitude, latitude) from map pin — WGS84', null=True, srid=4326)),
                ('theft_location_detail', models.TextField(blank=True, help_text='Free-text: street name, landmark, area', null=True)),
                ('fir_number', models.CharField(blank=True, help_text='Police FIR number if filed at station', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Owner narrative of theft circumstances', null=True)),
                ('status', models.CharField(choices=[('stolen', 'Stolen'), ('under_investigation', 'Under Investigation'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='stolen', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — evidence records are never hard-deleted', null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theft_reports', to='bikes.bike')),
            ],
            options={
                'db_table': 'theft_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
