# Generated by Django 4.2.11 on 2026-04-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theftreport',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.PROTECT, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='logged_by',
            field=models.ForeignKey(limit_choices_to={'role': 'authority'}, on_delete=django.db.models.deletion.PROTECT, related_name='logged_recoveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='theft_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recovery', to='reports.theftreport'),
        ),
    ]
