# Generated by Django 4.2.11 on 2026-04-22 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theftreport',
            name='authority_last_action_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Used for stale-case automation and reminders.'),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='owner_recovery_confirmed',
            field=models.BooleanField(default=False, help_text='Owner must confirm pickup/receipt before final case closure.'),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='owner_recovery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='owner_recovery_confirmed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_recoveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theftreport',
            name='stale_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='status',
            field=models.CharField(choices=[('new_case', 'New Case'), ('under_review', 'Under Review'), ('active_investigation', 'Active Investigation'), ('bike_located', 'Bike Located'), ('pending_verification', 'Pending Verification'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='new_case', max_length=30),
        ),
        migrations.CreateModel(
            name='CaseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theft_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='reports.theftreport')),
            ],
            options={
                'db_table': 'case_timeline',
                'ordering': ['created_at'],
            },
        ),
    ]
