# Generated by Django 4.2.11 on 2026-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_theftreport_authority_last_action_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theftreport',
            name='status',
            field=models.CharField(choices=[('stolen', 'Stolen (Legacy)'), ('under_investigation', 'Under Investigation (Legacy)'), ('new_case', 'New Case'), ('under_review', 'Under Review'), ('active_investigation', 'Active Investigation'), ('bike_located', 'Bike Located'), ('pending_verification', 'Pending Verification'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='new_case', max_length=30),
        ),
    ]
