# Generated by Django 4.2.11 on 2026-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlanalysiscache',
            name='analysis_type',
            field=models.CharField(choices=[('hotspot_clusters', 'Hotspot Clusters (DBSCAN)'), ('trend_analytics', 'Trend Analytics (pandas)'), ('recovery_zones', 'Recovery Zone Analysis (PostGIS)'), ('corridor_analysis', 'Theft-to-Recovery Corridor Analysis (DBSCAN)'), ('recovery_radius', 'Recovery Radius Statistics')], max_length=30),
        ),
    ]
