# Generated by Django 4.2.11 on 2026-04-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Context report — NULL for system notifications', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='reports.theftreport'),
        ),
    ]
