# Generated by Django 4.2.11 on 2026-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sightingreport_auto_escalated_and_more'),
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='sighting',
            field=models.ForeignKey(blank=True, help_text='Context sighting — used for owner handshake actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='sightings.sightingreport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('theft_reported', 'Theft Reported'), ('status_update', 'Status Update'), ('recovery', 'Vehicle Recovered'), ('sighting_matched', 'Sighting Matched'), ('sighting_owner_handshake', 'Sighting Owner Handshake'), ('sighting_owner_response', 'Sighting Owner Response'), ('community_closure', 'Community Closure'), ('system', 'System Notification'), ('urgent', 'Urgent Alert')], max_length=30),
        ),
    ]
