# Generated by Django 4.2.11 on 2026-04-13 17:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_engine_number', models.CharField(blank=True, help_text='What community reporter entered — may be partial or incorrect', max_length=50, null=True)),
                ('raw_chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fuzzy_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Best rapidfuzz score at submission time', max_digits=5, null=True)),
                ('sighting_date', models.DateField()),
                ('sighting_city', models.CharField(max_length=80)),
                ('sighting_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('sighting_description', models.TextField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, help_text='UUID filename of sighting photo stored in /media/sightings/', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='FALSE = unverified community report. TRUE = authority confirmed.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bike', models.ForeignKey(blank=True, help_text='FK → bikes — NULL until authority verifies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='bikes.bike')),
            ],
            options={
                'db_table': 'sighting_reports',
                'ordering': ['-fuzzy_match_score', '-created_at'],
            },
        ),
    ]
