# Generated by Django 4.2.11 on 2026-04-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sightings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='sighter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='top_match_bike',
            field=models.ForeignKey(blank=True, help_text='Best fuzzy match candidate — shown to authority for review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_match_sightings', to='bikes.bike'),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'authority'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
