# Generated by Django 4.2.11 on 2026-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingreport',
            name='auto_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='owner_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('yes', 'Yes'), ('no', 'No'), ('not_sure', 'Not Sure')], default='pending', help_text='Owner handshake status for top_match_bike owner confirmation', max_length=12),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='owner_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightingreport',
            name='owner_response_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
