# Generated by Django 4.2.11 on 2026-04-13 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Manufacturer: Honda, Yamaha, Suzuki, United, Road Prince', max_length=60)),
                ('model', models.CharField(help_text='Model name: CD 70, CG 125, YBR 125', max_length=60)),
                ('year', models.SmallIntegerField(help_text='Manufacturing year (4 digits)')),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='License plate — may change; not used as unique ID', max_length=20, null=True)),
                ('registration_city', models.CharField(blank=True, max_length=80, null=True)),
                ('engine_number', models.CharField(help_text='TRUE unique identifier — cannot legally be changed. Target of fuzzy matching.', max_length=50, unique=True)),
                ('chassis_number', models.CharField(help_text='Secondary unique identifier stamped on frame', max_length=50, unique=True)),
                ('photo_url', models.CharField(blank=True, help_text='UUID filename stored in /media/bikes/', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — cannot delete if active theft report', null=True)),
            ],
            options={
                'db_table': 'bikes',
                'ordering': ['-created_at'],
            },
        ),
    ]
